In [28]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from HullWhite import HullWhite
from scipy.optimize import fsolve
import pandas as pd

file_path   = 'bvolmatrix.xlsx'
sheet       = 'STRADDLE'
sheetf      = 'STRIKE'
sheeti      = 'BVOL'
df          = pd.read_excel(file_path, sheet_name=sheet,header=None)
dff         = pd.read_excel(file_path, sheet_name=sheetf,header=None)
dfi         = pd.read_excel(file_path, sheet_name=sheeti,header=None)
straddlesobs       = pd.DataFrame(df[[x for x in np.arange(4,16)]][3:22])
strikes            = pd.DataFrame(dff[[x for x in np.arange(4,16)]][3:22])
impliedVol         = pd.DataFrame(dfi[[x for x in np.arange(4,16)]][3:22])
straddlesobs.index     = df[1][3:22].values
strikes.index          = dff[1][3:22].values
impliedVol.index       = dfi[1][3:22].values
straddlesobs.index.name='Expiry'
strikes.index.name     ='Expiry'
impliedVol.index.name  ='Expiry' 
straddlesobs.columns   = [int(x) for x in df.iloc[1][4:16].values]
strikes.columns        = [int(x) for x in dff.iloc[1][4:16].values]
impliedVol.columns     = [int(x) for x in dfi.iloc[1][4:16].values]
# straddlesobs
sheeta      = 'ARTICLE'
dfff        = pd.read_excel(file_path, sheet_name=sheeta,header=None)
articleobs  = dfff[[x for x in np.arange(4,17)]][3:17]/10000
articleobs.index = dfff[1][3:17].values
articleobs.index.name = 'Expiry'
articleobs.columns = [int(x) for x in dfff.iloc[1][4:17].values]

straddlesobs=straddlesobs.iloc[4::,0::]
strikes = strikes.iloc[4::,0::]
impliedVol = impliedVol.iloc[4::,0::]

def monthoryear(x):
    if x<12:
        return f'{int(x)}M'
    else:
        return f'{int(x/12)}Y'
    

# X,Y = np.meshgrid(straddlesobs.columns/12, straddlesobs.index/12)
# fig = plt.figure(figsize=(16,16))
# ax = fig.add_subplot(111, projection='3d')
# ax.plot_surface(Y,X,straddlesobs.values)
# ax.set_xlabel('Expiry')
# ax.set_xticks((straddlesobs.index/12))
# ax.set_xticklabels([monthoryear(x) for x in straddlesobs.index])
# ax.set_ylabel('Tenor')
# ax.set_yticklabels([f'{int(x/12)}Y' for x in straddlesobs.columns])
# ax.set_yticks(straddlesobs.columns/12)
# ax.invert_xaxis()
# plt.show()

# fig = plt.figure(figsize=(8,8))
# X,Y = np.meshgrid(impliedVol.columns/12, impliedVol.index/12)
# ax = fig.add_subplot(111, projection='3d')
# ax.plot_surface(Y,X,impliedVol.values, alpha=0.9, color='red')

# ax.set_xlabel('Expiry')
# ax.set_xticks((straddlesobs.index/12))
# ax.set_xticklabels([monthoryear(x) for x in straddlesobs.index])
# ax.set_ylabel('Tenor')
# ax.set_yticks(straddlesobs.columns/12)
# ax.set_yticklabels([f'{int(x/12)}Y' for x in straddlesobs.columns])
# ax.invert_xaxis()
# plt.show()

straddlesobs

12        24        36        48        60        84        120  \
Expiry                                                                         
12      0.010752  0.011071  0.010830  0.010552  0.010277  0.009871  0.009192   
24      0.013589  0.013703  0.013483  0.013296  0.013149  0.012856  0.012383   
36      0.015670  0.015721  0.015569  0.015322  0.015101  0.014816  0.014332   
48      0.017333  0.017410  0.017124  0.016893  0.016684  0.016325  0.015782   
60      0.018740  0.018732  0.018434  0.018121  0.017847  0.017445  0.016872   
72      0.019882  0.019853  0.019501  0.019108  0.018778  0.018336  0.017756   
84      0.020701  0.020690  0.020202  0.019770  0.019501  0.019005  0.018433   
96      0.021405  0.021423  0.020934  0.020532  0.020198  0.019695  0.019061   
108     0.022113  0.022081  0.021576  0.021222  0.020834  0.020238  0.019532   
120     0.022635  0.022617  0.022130  0.021681  0.021280  0.020647  0.019880   
144     0.023643  0.023618  0.023126  0.022662  0.022172  0.021545  0.020649   
180     0.024718  0.024688  0.024150  0.023659  0.023074  0.022308  0.021329   
240     0.026641  0.026662  0.026023  0.025338  0.024617  0.023772  0.022558   
300     0.028357  0.028273  0.027603  0.026721  0.025915  0.024802  0.023530   
360     0.029905  0.029936  0.029071  0.028039  0.026982  0.025767  0.024167   

             144       180       240       300       360  
Expiry                                                    
12      0.009070  0.008867  0.008497  0.008346  0.008174  
24      0.012164  0.011795  0.011363  0.011125  0.010977  
36      0.014066  0.013601  0.013090  0.012865  0.012612  
48      0.015441  0.014911  0.014327  0.014022  0.013681  
60      0.016475  0.015902  0.015254  0.014865  0.014487  
72      0.017320  0.016673  0.015968  0.015543  0.015113  
84      0.017963  0.017245  0.016453  0.015985  0.015529  
96      0.018557  0.017774  0.016928  0.016450  0.015996  
108     0.018977  0.018149  0.017277  0.016782  0.016298  
120     0.019277  0.018396  0.017516  0.016983  0.016506  
144     0.019975  0.018975  0.018071  0.017504  0.016984  
180     0.020562  0.019431  0.018594  0.017945  0.017330  
240     0.021656  0.020314  0.019475  0.018755  0.017998  
300     0.022572  0.021144  0.019947  0.019185  0.018447  
360     0.023083  0.021471  0.020195  0.019557  0.018831

In [47]:
from scipy.optimize import minimize, basinhopping, fsolve
from NelsonSiegel import NelsonSiegel



def NSoptimizer(X1,X2,X3,Lambda, sigmaL, sigmaS, sigmaC, observedP, observedK):
    if (np.array([sigmaL, sigmaS, sigmaC])<0).any():
        print('Volatility is negative', end='\r')
        return 100000000
    
    # if X1+X2>0.03:
    #     return 100000000
    
    # if X1+X2<0.01:
    #     return 100000000

    straddleModel = observedP.copy()
    optNS = NelsonSiegel(initial=np.array([X1,X2,X3]),
                         Lambda=Lambda,
                         sigmaL=sigmaL,
                         sigmaS=sigmaS,
                         sigmaC=sigmaC
                        )

    for expiry in observedP.index:
        # Expiry first
        # Getting the right expiry and converting to years
        # Simulate the rates here:
        np.random.seed(1337)
        N = 1000
        rate = [optNS.oneStep(0,np.array([X1,X2,X3]), expiry/12, expiry/12) for _ in range(N)]


        for tenor in observedP.columns:
            # Creating tenor legs
            T = np.arange(expiry/12, expiry/12+tenor/12+0.5, 0.5)
            S = np.arange(expiry/12, expiry/12+tenor/12+1)
            # Finding the ATM fixed rate
            K = observedK[tenor].loc[expiry]/100
            # K = fsolve(lambda x: optHW.swap(0, S, T, x), x0=MarketATM)[0]
            swap = np.array([float(optNS.swap(expiry/12, S, T, K, x, payer=True)) for x in rate])
            #Calculating the payer and receiver swpt price
            p = optNS.ZCB(0,expiry/12)*np.maximum(swap,0).mean()
            r = -optNS.ZCB(0,expiry/12)*np.minimum(swap,0).mean()
            
            #Normalizing w.r.t. to the A(t,S) function (2.10) everythin you wanna know...
            A = np.array([optNS.ZCB(0, Si) for Si in S[1::]]).sum()

            straddleModel[tenor].loc[expiry] = (p+r)/A
            # if (p+r)*10000<0:
            # print(p,r,expiry,tenor,reversion,volatility)
            

    error = ((straddleModel/observedP-1)**2).sum().sum()
    print(f'\n{error}', end='                                                         \r')
    return error

In [38]:
NSoptimizer(0.04079043, 
            -0.01434756, 
            -0.01121523,  
            0.0203223 ,  
            0.04,
            0.004, 
            0.004, straddlesobs, strikes)

5.175238793982223e+19

In [40]:
-0.014079043 +0.03434756,

(0.020268517,)

In [48]:
function = lambda x: NSoptimizer(x[0],x[1],x[2],x[3],x[4], x[5], x[6], straddlesobs, strikes)

from scipy.optimize import minimize
Nfeval = 0
def callback(xk):
    global Nfeval
    print(f'\nEval: {Nfeval}, x={xk}')
    Nfeval += 1
    return True

res = minimize(fun = function, 
               x0= np.array([
                   -0.01191839, -0.02335278, -0.0091456, 0.47024185, 0.00364122, 0.0090127, 0.00602759
                   ]), 
               method='nelder-mead',
               tol = 1e-3,
               callback=callback)

res


8.483381779871214                                                         
8.261678516905372                                                         
8.664758385465603                                                         
9.13434503147917                                                         
8.28403955568128                                                         
8.48060536485593                                                         
8.945047843292144                                                         
9.049929410887383                                                         
9.310602072440945                                                         
8.64840521728343                                                         
Eval: 0, x=[-0.01251431 -0.02335278 -0.0091456   0.47024185  0.00364122  0.0090127
  0.00602759]

7.868897415811365                                                         
7.382492328683563                                                         
Eval:

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 3.3275415612574877
             x: [-2.926e-03 -3.672e-02 -9.667e-03  7.526e-02  1.504e-03
                  6.813e-03  5.688e-04]
           nit: 370
          nfev: 567
 final_simplex: (array([[-2.926e-03, -3.672e-02, ...,  6.813e-03,
                         5.688e-04],
                       [-3.022e-03, -3.659e-02, ...,  6.806e-03,
                         5.676e-04],
                       ...,
                       [-2.915e-03, -3.674e-02, ...,  6.774e-03,
                         5.741e-04],
                       [-2.850e-03, -3.677e-02, ...,  6.787e-03,
                         5.583e-04]]), array([ 3.328e+00,  3.328e+00,  3.328e+00,  3.328e+00,
                        3.328e+00,  3.328e+00,  3.328e+00,  3.328e+00]))

In [ ]:
#Negative rates but so far best fit
[-0.00292578, -0.03671727, -0.00966689,  0.07525687,  0.00150408,  0.00681309, 0.00056876]

In [ ]:
#Vol close to zero and error on 400 bad fit
2.01808358e-02 -1.01808105e-02 -1.14742745e-02  3.67142919e-01 2.49851945e-03  1.10238173e-02  2.33977720e-08

In [45]:
# not really getting under 650
function(
    np.array([-0.00257852,  0.01258157, -0.02474609,  0.13193816,  0.00704211,  0.01290958, 0.00579656])
    )

654.4450982953709

In [5]:
res.x
#eval 40

In [29]:
expiry = 5*12
tenor = 10*10


np.random.seed(1337)
testNS = NelsonSiegel(initial=np.array([res.x[0], res.x[1], res.x[2]]),
                         Lambda=res.x[3],
                         sigmaL=res.x[4],
                         sigmaS=res.x[5],
                         sigmaC=res.x[6]
                        )

T = np.arange(expiry/12, expiry/12+tenor/12+0.5, 0.5)
S = np.arange(expiry/12, expiry/12+tenor/12+1)
print(T)
print(S)
K = 0.04
N = 1000
rate = [testNS.oneStep(0,np.array([res.x[0], res.x[1], res.x[2]]), expiry/12, fwd=expiry/12) for _ in range(N)]
swap = [testNS.swap(expiry/12, S, T, K, initRate = x, payer=True) for x in rate]
p = np.maximum(swap,0).mean()
r = -np.minimum(swap,0).mean()
A = np.array([testNS.ZCB(0, Si) for Si in S[1::]]).sum()
(p+r)/A

[12.  12.5 13. ]
[12 13]


0.1409037927244361

In [19]:
from scipy.optimize import minimize, basinhopping, fsolve
from NelsonSiegel import NelsonSiegel



def NSoptimizer(X1,X2,X3,Lambda, sigmaL, sigmaS, sigmaC, observedP, observedK):
    if (np.array([sigmaL, sigmaS, sigmaC])<0).any():
        print('Volatility is negative', end='r')
        return 100000
    
    straddleModel = observedP.copy()
    optNS = NelsonSiegel(initial=np.array([X1,X2,X3]),
                         Lambda=Lambda,
                         sigmaL=sigmaL,
                         sigmaS=sigmaS,
                         sigmaC=sigmaC
                        )

    for expiry in observedP.index:
        # Expiry first
        # Getting the right expiry and converting to years
        # Simulate the rates here:
        np.random.seed(1337)
        N = 1000
        rate = [optNS.oneStep(0,np.array([X1,X2,X3]), expiry, expiry) for _ in range(N)]


        for tenor in observedP.columns:
            # Creating tenor legs
            T = np.arange(expiry/12, expiry/12+tenor/12+0.5, 0.5)
            S = np.arange(expiry/12, expiry/12+tenor/12+1)
            # Finding the ATM fixed rate
            K = observedK[tenor].loc[expiry]/100
            # K = fsolve(lambda x: optHW.swap(0, S, T, x), x0=MarketATM)[0]
            swap = np.array([float(optNS.swap(expiry/12, S, T, K, x, payer=True)) for x in rate])
            #Calculating the payer and receiver swpt price
            p = optNS.ZCB(0,expiry/12)*np.maximum(swap,0).mean()
            r = -optNS.ZCB(0,expiry/12)*np.minimum(swap,0).mean()
            
            #Normalizing w.r.t. to the A(t,S) function (2.10) everythin you wanna know...
            A = np.array([optNS.ZCB(0, Si) for Si in S[1::]]).sum()

            straddleModel[tenor].loc[expiry] = (p+r)/A
            # if (p+r)*10000<0:
            # print(p,r,expiry,tenor,reversion,volatility)
            

    error = ((straddleModel/observedP-1)**2).sum().sum()
    print(f'{error}', end='                                                         \r')
    return straddleModel,error
resultStraddle, resultError = NSoptimizer(X1=res.x[0],X2=res.x[1],X3=res.x[2],Lambda=res.x[3], sigmaL=res.x[4], sigmaS=res.x[5], sigmaC=res.x[6], observedP=straddlesobs, observedK=strikes)

In [20]:
resultStraddle

12   24   36   48   60   84   120       144       180       240  \
Expiry                                                                    
12      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.008116  0.010006  0.008227   
24      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
36      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
48      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
60      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
72      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
84      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
96      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
108     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
120     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
144     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
180     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
240     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
300     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   
360     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000   

             300       360  
Expiry                      
12      0.008076  0.008484  
24      0.012021  0.009854  
36      0.000000  0.000000  
48      0.000000  0.000000  
60      0.000000  0.000000  
72      0.000000  0.000000  
84      0.000000  0.000000  
96      0.000000  0.000000  
108     0.000000  0.000000  
120     0.000000  0.000000  
144     0.000000  0.000000  
180     0.000000  0.000000  
240     0.000000  0.000000  
300     0.000000  0.000000  
360     0.000000  0.000000

In [ ]:
# a=testNS.create_path(1/12,1)
a=[testNS.init]

a.append(testNS.oneStep(0,np.array(a[0]),1/12).flatten())
a.append(testNS.oneStep(0,np.array(a[1]),1/12).flatten())

In [15]:
float = testNS.create_path(1/12, 10,fwd=0,seed=1)[1]
# D = np.insert(np.exp(-float[:-1:]*time[1::]),0,1)
D = np.cumprod(np.insert(np.exp(-float[:-1:].sum(axis=-1)*(1/12)),0,1))
swap = np.array([testNS.swapextended(t, S, T, K=K, floatRate=float, schedule=time, initRate=x) for t,x in zip(time,float)])
# print('{:.2f}%'.format(round(i/sims*100, 2)), end='\r')
D*np.maximum(swap,0), D*np.minimum(swap,0)

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.01854523,
        0.03724271, 0.04956396, 0.06615942, 0.08404276, 0.09374031,
        0.10595095, 0.1087683 , 0.12195968, 0.13056189, 0.13855021,
        0.13877469, 0.14214487, 0.14770455, 0.14436006, 0.14597567,
        0.149913  , 0.15844003, 0.16748002, 0.17482281, 0.16926797,
        0.16940544, 0.15945703, 0.1592518 , 0.16457722, 0.15893138,
        0.15775047, 0.14660328, 0.13226183, 0.17

In [14]:
time

array([ 0.        ,  0.08333333,  0.16666667,  0.25      ,  0.33333333,
        0.41666667,  0.5       ,  0.58333333,  0.66666667,  0.75      ,
        0.83333333,  0.91666667,  1.        ,  1.08333333,  1.16666667,
        1.25      ,  1.33333333,  1.41666667,  1.5       ,  1.58333333,
        1.66666667,  1.75      ,  1.83333333,  1.91666667,  2.        ,
        2.08333333,  2.16666667,  2.25      ,  2.33333333,  2.41666667,
        2.5       ,  2.58333333,  2.66666667,  2.75      ,  2.83333333,
        2.91666667,  3.        ,  3.08333333,  3.16666667,  3.25      ,
        3.33333333,  3.41666667,  3.5       ,  3.58333333,  3.66666667,
        3.75      ,  3.83333333,  3.91666667,  4.        ,  4.08333333,
        4.16666667,  4.25      ,  4.33333333,  4.41666667,  4.5       ,
        4.58333333,  4.66666667,  4.75      ,  4.83333333,  4.91666667,
        5.        ,  5.08333333,  5.16666667,  5.25      ,  5.33333333,
        5.41666667,  5.5       ,  5.58333333,  5.66666667,  5.75

In [16]:
np.array([time,float])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
time, float

(array([ 0.        ,  0.08333333,  0.16666667,  0.25      ,  0.33333333,
         0.41666667,  0.5       ,  0.58333333,  0.66666667,  0.75      ,
         0.83333333,  0.91666667,  1.        ,  1.08333333,  1.16666667,
         1.25      ,  1.33333333,  1.41666667,  1.5       ,  1.58333333,
         1.66666667,  1.75      ,  1.83333333,  1.91666667,  2.        ,
         2.08333333,  2.16666667,  2.25      ,  2.33333333,  2.41666667,
         2.5       ,  2.58333333,  2.66666667,  2.75      ,  2.83333333,
         2.91666667,  3.        ,  3.08333333,  3.16666667,  3.25      ,
         3.33333333,  3.41666667,  3.5       ,  3.58333333,  3.66666667,
         3.75      ,  3.83333333,  3.91666667,  4.        ,  4.08333333,
         4.16666667,  4.25      ,  4.33333333,  4.41666667,  4.5       ,
         4.58333333,  4.66666667,  4.75      ,  4.83333333,  4.91666667,
         5.        ,  5.08333333,  5.16666667,  5.25      ,  5.33333333,
         5.41666667,  5.5       ,  5.58333333,  5.6

In [33]:
np.array(a)

array([[0.00450864, 0.00447636, 0.01101805],
       [0.0051715 , 0.00682231, 0.00981823],
       [0.00559638, 0.01832821, 0.0092781 ]])

In [9]:
stepfrom = np.array([0.02,0.001,0.003])
stepsize = 1/12
Z = np.random.normal(loc=0,scale=1, size=3).reshape(3,1)

KQ = np.array([
    [0, 0, 0],
    [0, 0.9, -0.9],
    [0,0,0.9]
    ]).reshape(3,3)

ThetaQ = np.array([[0],[0],[0]]).reshape(3,1)

Sigma = np.array([
    [0.01, 0, 0],
    [0, 0.02, 0],
    [0,0,0.03]
    ]).reshape(3,3)

stepfrom.reshape(3,1) + np.matmul(KQ,ThetaQ - stepfrom.reshape(3,1))*stepsize + np.matmul(Sigma, np.sqrt(stepsize)*(Z-Sigma @ testNS.B(0, 1).reshape(3,1)))


array([[0.02085364],
       [0.0006923 ],
       [0.00242592]])

In [10]:
testNS.oneStep(0,a[0],1/12)

AttributeError: 'list' object has no attribute 'reshape'

In [67]:
np.array([0.00450864, 0.00447636, 0.01101805, 0.73963909, 0.00179664,
       0.03077568, 0.00100149])

5.643432267358449

In [11]:
float(testNS.swap(5,S,T, K ,rate[0], payer=True))

0.9676504120950497

In [12]:
swap

[0.9676504120950497,
 0.965369756223179,
 0.9663215052009619,
 0.9673772390246638,
 0.9680196940127614,
 0.9657540645613312,
 0.9669254871687996,
 0.9675132457394671,
 0.9657426497496099,
 0.9674840747719028,
 0.9702461153600939,
 0.9643314924686437,
 0.9677553941464005,
 0.9672446663320488,
 0.9679446461114981,
 0.9667813674524832,
 0.9658058179143235,
 0.9696197212154114,
 0.9643015975536132,
 0.9699483046872828,
 0.9656766938090664,
 0.9683095926850059,
 0.9687282066845759,
 0.9678423280872064,
 0.964520140816875,
 0.9684582479402766,
 0.9669402026531998,
 0.9665953302532933,
 0.9691462290920086,
 0.9646033339059333,
 0.9667771408782098,
 0.9677541092973426,
 0.9700467264030386,
 0.9674157427788875,
 0.96416212996251,
 0.9655076164364216,
 0.9681501188669667,
 0.9651910682454256,
 0.9656462576831573,
 0.9648500405860606,
 0.9662574794729338,
 0.9644825369650433,
 0.9648075526856307,
 0.9665440025861133,
 0.9639616448518511,
 0.9672069987491504,
 0.9664742100783493,
 0.96958365777427