In [2]:
import numpy as np
np.arange(0,10.5,0.5, )

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [1]:
tester = np.array([1,4,3,4,5])
tester, np.where(tester == 4)

NameError: name 'np' is not defined

In [2]:
import numpy as np
np.arange(1,5)

array([1, 2, 3, 4])

In [5]:
np.maximum(np.arange(1,5),2)

array([2, 2, 3, 4])

In [1]:
4*3**2

36

In [1]:
1/(1/12)

12.0